{
 "title": "Wess",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(wess_http_request_latency_seconds_bucket[1m])))",
     "legendFormat": "99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(wess_http_request_latency_seconds_bucket[1m])))",
     "legendFormat": "95"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le) (rate(wess_http_request_latency_seconds_bucket[1m])))",
     "legendFormat": "90"
    }
   ]
  },
  {
   "title": "Database Ops READ",
   "type": "stat",
   "gridPos": { "h": 11, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wess_database_operations_total{operation=\"read\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Ops WRITE",
   "type": "stat",
   "gridPos": { "h": 11, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wess_database_operations_total{operation=\"write\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WASM Compile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(wess_wasm_compile_time_seconds[1m])))",
     "legendFormat": "99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(wess_wasm_compile_time_seconds[1m])))",
     "legendFormat": "95"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le) (rate(wess_wasm_compile_time_seconds[1m])))",
     "legendFormat": "90"
    }
   ]
  },
  {
   "title": "WASM Execution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(wess_wasm_execution_time_seconds[1m])))",
     "legendFormat": "99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(wess_wasm_execution_time_seconds[1m])))",
     "legendFormat": "95"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le) (rate(wess_wasm_execution_time_seconds[1m])))",
     "legendFormat": "90"
    }
   ]
  },
  {
   "title": "Writer Channel Queue",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wess_writer_channel_queue * -1 + 10000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Writer Channel Queue",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wess_reader_channel_queue * -1 + 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Concurrent Connections",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "wess_concurrent_connections", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wess_http_requests_total{path=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}