[server]
port = 80
address = "0.0.0.0"

[database]
db = "rocksdb"
stage = "dev"

[reader]
cache_size = 1024
channel_size = 1024

[writer]
channel_size = 1024

[runner]
cache_size = 1024
channel_size = 100
