server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /etc/promtail/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: wess
    static_configs:
      - targets:
          - localhost
        labels:
          job: wess
          __path__: /var/log/wess/*.log
