global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "wess"
    static_configs:
      - targets: ['127.0.0.1:7770']
      # - targets: ['host.docker.internal:7770'] for run wess outside docker
