services:
  wess:
    image: olivmath/wess
    volumes:
      - rocksdb:/etc/rocksdb
      - logs:/etc/wess/logs
    ports:
      - "7770:80"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./alert-rules.yml:/etc/prometheus/alert-rules.yml
      - ../prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - besu

  alertmanager:
    image: prom/alertmanager:latest
    volumes:
      - ./alert-manager.yml:/prometheus/alert-manager.yml
    command:
      - "--config.file=/prometheus/alert-manager.yml"
    ports:
      - "9093:9093"
    depends_on:
      - prometheus

  grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - "3000:3000"

volumes:
  grafana-storage:
  rocksdb:
  logs:
